###################################################
###################################################
# Make sure to only modify the template file!!!!!!!
###################################################
###################################################

sudo: required
services:
  - docker
language: generic
install: true
branches:
  only:
    - master
script:
  - ./scripts/build_image shinylearner
  - echo "$DOCKER_PASS" | sudo docker login -u="$DOCKER_USER" --password-stdin
  - sudo docker push srp33/shinylearner:version630
